// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestingTemplates.Models;

public partial class Robot
{
    public int RobidPk { get; set; }

    public string RobDescription { get; set; }

    public string RobType { get; set; }

    public string RobColor { get; set; }

    public int RobStatus { get; set; }
}